// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Testing.Tests")>]
[<assembly: AssemblyProductAttribute("Testing")>]
[<assembly: AssemblyVersionAttribute("0.1.5")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2020-01-28T00:00:00.0000000+07:00")>]
[<assembly: AssemblyFileVersionAttribute("0.1.5")>]
[<assembly: AssemblyInformationalVersionAttribute("0.1.5")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","296ae07f79998e5a1bb356514adddabee55b8629")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Testing.Tests"
    let [<Literal>] AssemblyProduct = "Testing"
    let [<Literal>] AssemblyVersion = "0.1.5"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2020-01-28T00:00:00.0000000+07:00"
    let [<Literal>] AssemblyFileVersion = "0.1.5"
    let [<Literal>] AssemblyInformationalVersion = "0.1.5"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "296ae07f79998e5a1bb356514adddabee55b8629"
