// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Testing.Tests")>]
[<assembly: AssemblyProductAttribute("Testing")>]
[<assembly: AssemblyVersionAttribute("0.1.3")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2020-01-28T00:00:00.0000000+07:00")>]
[<assembly: AssemblyFileVersionAttribute("0.1.3")>]
[<assembly: AssemblyInformationalVersionAttribute("0.1.3")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","rc")>]
[<assembly: AssemblyMetadataAttribute("GitHash","d413f27094c659f9781cf41e1a201df1402d753d")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Testing.Tests"
    let [<Literal>] AssemblyProduct = "Testing"
    let [<Literal>] AssemblyVersion = "0.1.3"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2020-01-28T00:00:00.0000000+07:00"
    let [<Literal>] AssemblyFileVersion = "0.1.3"
    let [<Literal>] AssemblyInformationalVersion = "0.1.3"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "rc"
    let [<Literal>] AssemblyMetadata_GitHash = "d413f27094c659f9781cf41e1a201df1402d753d"
