// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Testing")>]
[<assembly: AssemblyProductAttribute("Testing")>]
[<assembly: AssemblyVersionAttribute("0.1.8")>]
[<assembly: AssemblyMetadataAttribute("ReleaseDate","2020-01-28T00:00:00.0000000+07:00")>]
[<assembly: AssemblyFileVersionAttribute("0.1.8")>]
[<assembly: AssemblyInformationalVersionAttribute("0.1.8")>]
[<assembly: AssemblyMetadataAttribute("ReleaseChannel","release")>]
[<assembly: AssemblyMetadataAttribute("GitHash","1d745e7979208893804100508a2c73b2d2404cbf")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Testing"
    let [<Literal>] AssemblyProduct = "Testing"
    let [<Literal>] AssemblyVersion = "0.1.8"
    let [<Literal>] AssemblyMetadata_ReleaseDate = "2020-01-28T00:00:00.0000000+07:00"
    let [<Literal>] AssemblyFileVersion = "0.1.8"
    let [<Literal>] AssemblyInformationalVersion = "0.1.8"
    let [<Literal>] AssemblyMetadata_ReleaseChannel = "release"
    let [<Literal>] AssemblyMetadata_GitHash = "1d745e7979208893804100508a2c73b2d2404cbf"
