name: get-version-number

on:
  push:
    branches: [ master, qa, live, fieldworks8-master, fieldworks8-qa, fieldworks8-live ]
  pull_request:
    branches: [ master, fieldworks8-master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.0.0
        with:
          fetch-depth: 0  # All history for all tags and branches, since branch calculation step needs that

      - name: Calculate version number
        run: ./get-version-number.sh
