# This is a basic workflow to help you get started with Actions

name: Nuget-CI-CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ mercurial-zstd ]
  #   branches: [ master ]
  # pull_request:
  #   branches: [ master ]

# Cancel any workflow jobs running if the PR is re-triggered
concurrency:
  group: ci-${{ github.head_ref }}-group
  cancel-in-progress: true

jobs:
  build-python:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
    steps:
    - name: Setup Python
      uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Python setuptools
      run: pip install setuptools
    - name: Checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
    - name: Build zstd module
      working-directory: linux-x64/Mercurial/contrib/python-zstandard
      run: python3 setup.py build
    - name: Prepare for upload
      # actions/upload-artifact preserves directory names starting from first wildcard
      # But while we can't quite predict the name of the lib.linux-x86_64-* directory, we don't actually want it preserved
      # So we move the zstd.cpython-*-x86_64-linux-gnu.so file(s) into a common directory prior to upload
      run: mv linux-x64/Mercurial/contrib/python-zstandard/build/lib.linux-x86_64-*/zstd.cpython-*-x86_64-linux-gnu.so linux-x64/Mercurial/contrib/python-zstandard/build/
    - name: Upload zstd module
      uses: actions/upload-artifact@1746f4ab65b179e0ea60a494b83293b640dd5bba # v4.3.2
      with:
        name: zstd-for-python-${{ matrix.python-version }}
        path: linux-x64/Mercurial/contrib/python-zstandard/build/zstd.cpython-*-x86_64-linux-gnu.so
        if-no-files-found: error

  build:
    runs-on: ubuntu-latest
    needs: build-python
    steps:
    - name: Checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        fetch-depth: 0
    - name: Set Beta Version
      if: github.event_name != 'push'
      run: echo "release-suffix=-beta" >> $GITHUB_ENV
    - name: Set Release Version
      if: github.event_name == 'push'
      run: echo "release-suffix=." >> $GITHUB_ENV

    - name: Download zstd modules
      uses: actions/download-artifact@8caf195ad4b1dee92908e23f56eeb0696f1dd42d # v4.1.5
      with:
        path: linux-x64/Mercurial/mercurial/
        pattern: zstd-for-python-*
        merge-multiple: true

    - name: Check zstd module download
      working-directory: linux-x64/Mercurial/mercurial
      run: ls -l zstd.cpython*

    # TODO: Ensure the contrib/python-zstandard/zstandard directory (and its .py files) ends up alongside those, then make sure it gets into the NuGet package

    - name: Nuget pack
      run: dotnet msbuild -target:Build build/SIL.Chorus.Mercurial.proj -property:PreRelease=${{ env.release-suffix }} -property:BuildCounter=${{ github.run_number }}

    - name: Upload Artifacts
      uses: actions/upload-artifact@1746f4ab65b179e0ea60a494b83293b640dd5bba # v4.3.2
      with:
        name: packages
        path: ./**/*.nupkg
        if-no-files-found: error
