name: release

on:
  workflow_call:
    inputs:
      MsBuildVersion:
        required: true
        type: string
      FW8Branch:
        required: true
        type: string
      FW9Branch:
        required: true
        type: string
      TagFor7000068:
        required: true
        type: string
      TagFor7000069:
        required: true
        type: string
      TagFor7000070:
        required: true
        type: string
      TagFor7000072:
        required: true
        type: string

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.4.0
      with:
        fetch-depth: 0

    - name: Ensure all TagForDbVersion outputs were present
      env:
        TAG68: ${{ inputs.TagFor7000068 }}
        TAG69: ${{ inputs.TagFor7000069 }}
        TAG70: ${{ inputs.TagFor7000070 }}
        TAG72: ${{ inputs.TagFor7000072 }}
      run: |
        echo "Tag for 68: (${TAG68})"
        echo "Tag for 69: (${TAG69})"
        echo "Tag for 70: (${TAG70})"
        echo "Tag for 72: (${TAG72})"

    - name: Tag release branches
      if: github.event_name == 'push' && github.ref == 'refs/heads/live'
      env:
        FW8Branch: ${{ inputs.FW8Branch }}
        FW9Branch: ${{ inputs.FW9Branch }}
        TAG70: ${{ inputs.TagFor7000070 }}
        TAG72: ${{ inputs.TagFor7000072 }}
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git tag -a -m "Release ${TAG70}" "${TAG70}" "${FW8Branch}"
        git tag -a -m "Release ${TAG72}" "${TAG72}" "${FW9Branch}"
        git push -v origin "${TAG70}" "${TAG72}"

    # - name: Download build artifacts
    #   uses: actions/download-artifact@v2.0.10
    #   with:
    #     name: lfmerge-tarball
    #     path: tarball

    # - name: Ensure all parts of final tarball exist
    #   # TODO: Should no longer be needed; verify, then remove
    #   run: |
    #     mkdir -p tarball/lfmerge-7000068 || true
    #     mkdir -p tarball/lfmerge-7000069 || true
    #     mkdir -p tarball/lfmerge-7000070 || true
    #     mkdir -p tarball/lfmerge-7000072 || true
    #     mkdir -p tarball/lfmerge || true

    # - name: Login to GHCR
    #   if: github.event_name == 'push' && github.ref == 'refs/heads/live'
    #   uses: docker/login-action@v1
    #   with:
    #     registry: ghcr.io
    #     username: ${{ github.repository_owner }}
    #     password: ${{ secrets.GITHUB_TOKEN }}

    # - name: Build final Docker image
    #   id: lfmerge_image
    #   # docker/build-push-action@v2.7.0 is commit a66e35b9cbcf4ad0ea91ffcaf7bbad63ad9e0229
    #   uses: docker/build-push-action@a66e35b9cbcf4ad0ea91ffcaf7bbad63ad9e0229
    #   # TODO: Follow https://github.com/docker/build-push-action/blob/master/docs/advanced/tags-labels.md for tagging
    #   with:
    #     push: ${{(github.event_name == 'push' && github.ref == 'refs/heads/live')}}
    #     tags: ghcr.io/sillsdev/lfmerge:${{ inputs.MsBuildVersion }},ghcr.io/sillsdev/lfmerge:latest
    #     context: .
    #     file: Dockerfile.finalresult

    # - name: Show metadata from LfMerge image build step
    #   run: echo "$METADATA"
    #   env:
    #     METADATA: ${{ steps.lfmerge_image.output.metadata }}

    # - name: List Docker images to verify build
    #   run: docker image ls
